### PR TITLE
Allows opening file from command line

### PR DESCRIPTION
**Pull request by diogovk**
Also adds options --help and --version

Please tell me your thoughts.

### CODE REVIEW

**Comment by mathall** [comment]
Cool, a couple of notes and issues:

1) You'd want to update the Cargo.lock file when adding new dependencies. This file specifies which revision of all the dependencies we want to be used. So just build once, make sure it works, then check in the lock with the rest.

2) I don't like duplicating the version number like this. Either we need a way to maybe extract it from the toml, or we just skip the version flag for now as it's kind of a nonsense number at the moment anyway.

3) You could unify two of the usages by making the file argument optional: `rim [<file>]`

4) I'd actually prefer sticking the USAGE text and everything either right over main or at the top of rim.rs. I don't think the separate module is justified here.

5) Lets discuss that tag line, I'm not a fan of calling rim "advanced." :P Just "Text editor" may be fine but dull, "TUI text editor" maybe? Or Vim-style? (vim is almost a "genre" by now isn't it?)

6) Did you try the docopt! macro? I'm not sure that's better, maybe it just gets confusing. I'm just curious if you did and if you had any thoughts on it.

**Comment by diogovk** [comment]
> 1)

Done

> 2)

Done

> 3)

I was looking for this. So easy!
Done

> 4)

Done it. Much better this way.

> 5)

Done

> 6)

I don't have a strong preference in this matter. Both options look fine to me.
The macro requires "unstable features", which means it might break in the future.
When using the macro the code feels "cleaner" even if not as explicit.
It's up to you to decide. If you want the macro I'll do using the macro.

**Comment by mathall** [comment]
2) Nice!
6) Great, agreed. Let's skip the macro then.

I have some minor tweaks I'd like to get your input on before putting it on master: https://github.com/mathall/rim/commits/parse_cmdline
Any objections before I squash and merge?

**Comment by diogovk** [comment]
> Any objections?

Not at all. Looks great!

**Comment by mathall** [comment]
suh-weet
Pushed to master then.

**Pull request closed without merging**
